Repository ScoopInstaller/Main, pull requests merged in 2020-08, with the labels that each got.

#1313 ensubst: Add version 1.2.0
  bucket/envsubst.json
Labels: review-needed

#1330 gbt: Add version 2.0.0
  bucket/gbt.json
Labels: please-review, review-needed

#1305 nextdns: Add version 1.7.1
  bucket/nextdns.json
Labels: please-review
