Repository ScoopInstaller/Main, pull requests merged in 2020-09, with the labels that each got.

#1389 imagemagick@7.0.10-29: Fix shimed bin
  bucket/imagemagick.json
Labels: review-needed

#1390 tinygo: Add version 0.14.1
  bucket/tinygo.json
Labels: review-needed

#1350 Add ccache manifest
  bucket/ccache.json
Labels: review-needed

#1348 kind: Add version 0.8.1
  bucket/kind.json
Labels: review-needed

#1366 fossil: Update to version 2.12.1
  bucket/fossil.json
Labels: review-needed

#1363 Add gdb-9.1-3 for gcc package
  bucket/gcc.json
Labels: please-review, review-needed

#1182 ibmcloud-cli: Add version 1.1.0
  bucket/ibmcloud-cli.json
Labels: review-needed

#1362 android-clt: Add version 6609375
  bucket/android-clt.json
Labels: review-needed

#1360 gopass: Update to version 1.10.0
  bucket/gopass.json
Labels: package-fix-needed

#1359 pdfbox: Update to version 2.0.21
  bucket/pdfbox.json
Labels: review-needed

#1399 pypy(2, 3): fix download url
  bucket/pypy2.json
  bucket/pypy3.json
Labels: review-needed

#1398 lua: Update to version 5.4.0
  bucket/lua.json
Labels: review-needed

#1283 graphviz: Update to version 2.44.1
  bucket/graphviz.json
Labels: please-review

#1395 aws: Update to version 2.0.50
  bucket/aws.json
Labels: review-needed

#1431 mro: Fix `url` and `rtools` dep
  bucket/mro.json
Labels: review-needed

#1437 sd: Add version 0.7.5
  bucket/sd.json
Labels: package-fix-needed

#1428 csview: Add version 0.3.5
  bucket/csview.json
Labels: review-needed

#1316 poppler: Update to version 0.90
  bucket/poppler.json
Labels: please-review, review-needed
