Repository ScoopInstaller/Main, pull requests merged in 2020-07, with the labels that each got.

#1229 balena-cli: Add version 12.3.3
  bucket/balena-cli.json
Labels: review-needed

#1240 msys2: Update to version 20200629
  bucket/msys2.json
Labels: please-review, review-needed

#1147 vswhere: Add version 2.8.4
  bucket/vswhere.json
Labels: upstream

#1288 zoxide: Add version 0.4.3
  bucket/zoxide.json
Labels: package-fix-needed

#1217 ipopt: Add version 3.13.2
  bucket/ipopt.json
Labels: review-needed

#1286 clink.json: notes: correct the "clink autorun"
  bucket/clink.json
Labels: review-needed

#1292 prince: Add version 13.5
  bucket/prince.json
Labels: review-needed
