Repository ScoopInstaller/Main, pull requests merged in 2020-10, with the labels that each got.

#1474 signal-cli: Add version 0.6.10
  bucket/signal-cli.json
Labels: review-needed

#1448 Fix pypy2 7.3.2 URL
  bucket/pypy2.json
Labels: review-needed

#1472 brename: Add version 2.11.0
  bucket/brename.json
Labels: review-needed

#1434 v2ray: update homepage
  bucket/v2ray.json
Labels: package-fix-needed

#1487 Micronaut version updated to 2.1.0
  bucket/micronaut.json
Labels: package-fix-needed

#1499 ugrep: add version 3.0.2
  bucket/ugrep.json
Labels: review-needed

#1500 LLVM: Update to version 11.0.0
  bucket/llvm.json
Labels: review-needed

#1501 bit: Add version 0.5.14
  bucket/bit.json
Labels: package-fix-needed

#1504 udpate to pandoc 2.11.0.1
  bucket/pandoc.json
Labels: review-needed

#1510 glow: add version 1.0.2
  bucket/glow.json
Labels: review-needed

#1036 gdb: Update to version 9.1-3
  bucket/gdb.json
Labels: review-needed

#1031 gcc: Update to version 9.3.0-2
  bucket/gcc.json
Labels: review-needed

#1522 postgresql: Update to version 13.0
  bucket/postgresql.json
Labels: package-fix-needed

#1512 boundary: add version 0.1.0
  bucket/boundary.json
Labels: review-needed

#1511 waypoint: add version 0.1.3
  bucket/waypoint.json
Labels: review-needed

#1502 avrdude: Add version 6.3-20171130
  bucket/avrdude.json
Labels: review-needed

#1469 azure-cli: Set AzureCLIPath environment variable
  bucket/azure-cli.json
Labels: package-fix-needed

#1450 Create x265.json
  bucket/x265.json
Labels: review-needed

#1463 fixes vulkan sdk environment variables
  bucket/vulkan.json
Labels: package-fix-needed

#1405 latexindent: Add version 3.8.2
  bucket/latexindent.json
Labels: review-needed

#1369 Add Intermodal v0.1.10
  bucket/intermodal.json
Labels: package-fix-needed

#1357 wkhtmltopdf: Update to version 0.12.6-1
  bucket/wkhtmltopdf.json
Labels: package-fix-needed

#1354 cuda: Update to version 11.0.3_451.82
  bucket/cuda.json
Labels: package-fix-needed

#1289 abc: Add version 1.0.0-beta.1
  bucket/abc.json
Labels: package-fix-needed

#1216 elm: Change depends to nodejs-lts
  bucket/elm.json
Labels: please-review
