Repository ScoopInstaller/Main, pull requests merged in 2021-11, with the labels that each got.

#981 crc: Add version 1.34.0-4.9.0
  bucket/crc.json
Labels: review-needed

#2877 Fix dmd64 bin for 64bits system #2565
  bucket/dmd.json
Labels: review-needed

#1050 far: Use portable configuration
  bucket/far.json
Labels: review-needed

#2847 Autoupdate manifest 2845
  bucket/apimtemplate.json
  bucket/dhall.json
  bucket/dnscrypt-proxy.json
  bucket/fio.json
  bucket/k0s.json
  bucket/megatools.json
  bucket/mockery.json
  bucket/pngquant.json
  bucket/rainbow.json
  bucket/uutils-coreutils.json
Labels: review-needed

#2890 invoke-build: update checkver
  bucket/invoke-build.json
Labels: review-needed

#2892 megacmd: fix checkver
  bucket/megacmd.json
Labels: review-needed

#2888 pelook: Add version 1.73
  bucket/pelook.json
Labels: review-needed

#2895 hadolint: Update to version 2.8.0
  bucket/hadolint.json
Labels: review-needed, package update

#2903 mysql: Suggest vcredist2017 (closes #1074)
  bucket/mysql.json
Labels: review-needed

#2912 xxcopy: Fix license
  bucket/xxcopy.json
Labels: review-needed

#2914 Update OpenOCD version to 0.11.0 (20210729)
  bucket/openOCD.json
Labels: review-needed

#2915 questdb: Add version 6.0.9
  bucket/questdb.json
Labels: review-needed

#624 oracle-instant-client: Add version 21.3.0.0.0
  bucket/oracle-instant-client.json
Labels: review-needed

#2922 railway: Update to version 0.2.49
  bucket/railway.json
Labels: review-needed

#2924 PowerSession: Update to version 1.4.4
  bucket/PowerSession.json
Labels: review-needed

#2925 PowerSession: Update to version 1.4.5
  bucket/PowerSession.json
Labels: review-needed

#2926 Add clink utils
  bucket/clink-completions.json
  bucket/clink-flex-prompt.json
Labels: review-needed

#2928 yt-dlp: Update to version 2021.11.10.1
  bucket/yt-dlp.json
Labels: review-needed

#2929 luarocks: Add version 3.8.0
  bucket/luarocks.json
Labels: review-needed

#2941 clangd: Add version 13.0.0
  bucket/clangd.json
Labels: review-needed

#2942 kustomize: update to 4.4.1
  bucket/kustomize.json
Labels: review-needed

#2910 oracle-instant-client: Add SDK and ODBC
  bucket/oracle-instant-client-odbc.json
  bucket/oracle-instant-client-sdk.json
Labels: review-needed

#2918 modern7z: Add version 1.8.7
  bucket/modern7z.json
Labels: review-needed

#2946 fselect: Add version 0.7.7
  bucket/fselect.json
Labels: review-needed

#2947 wormhole-william: Add version 1.0.5
  bucket/wormhole-william.json
Labels: review-needed

#826 v: Add version 0.2.4
  bucket/v.json
Labels: review-needed

#2954 chore: rename manifest - beef and zig
  bucket/beef.json
  bucket/zig.json
Labels: review-needed

#2960 neovim-nightly: Remove 32bit and add au.hash
  bucket/neovim-nightly.json
  bucket/neovim.json
Labels: review-needed

#2962 sget: Add version 1.3.1
  bucket/sget.json
Labels: review-needed

#2967 gcc: Use WinLibs build and update to 11.2.0
  bucket/gcc.json
Labels: review-needed

#2968 Update okteto version
  bucket/okteto.json
Labels: review-needed

#2971 openssh: Change to Microsoft build and update to 8.6.0.0p1
  bucket/openssh.json
  bucket/win32-openssh.json
Labels: review-needed

#2979 Add tectonic to bucket
  bucket/tectonic.json
Labels: review-needed

#2980 hugo-extended: Update to version 0.89.4
  bucket/hugo-extended.json
Labels: review-needed

#2983 k9s: update to version 0.25.4
  bucket/k9s.json
Labels: review-needed

#2984 ryzenadj: Add version 0.8.2
  bucket/ryzenadj.json
Labels: review-needed

#2985 nu: update to version 0.40.0
  bucket/nu.json
Labels: review-needed

#2989 Update scrcpy to v1.20
  bucket/scrcpy.json
Labels: review-needed

#2994 ffmpeg and ffmpeg-shared: Fixed URl and hash
  bucket/ffmpeg-shared.json
  bucket/ffmpeg.json
Labels: review-needed

#2995 tinygo: Update to v0.21
  bucket/tinygo.json
Labels: review-needed

#2999 oh-my-posh3: Update to version 6.11.2 and fix url
  bucket/oh-my-posh3.json
Labels: review-needed

#3002 offlineinsiderenroll: Add version 2.6.2
  bucket/offlineinsiderenroll.json
Labels: review-needed

#3008 get-iplayer: Add version 3.27.1
  bucket/get-iplayer.json
Labels: review-needed

#3009 lessmsi: Update to v1.10.0
  bucket/lessmsi.json
Labels: review-needed

#3010 hugo: Update to version 0.89.4
  bucket/hugo.json
Labels: review-needed

#3012 fd@8.3.0: Fix missing fd.exe
  bucket/fd.json
Labels: review-needed

#3011 sentinel: Add version 0.18.4
  bucket/sentinel.json
Labels: review-needed

#3013 k9s: update to version 0.25.7
  bucket/k9s.json
Labels: review-needed

#3017 mingit & mingit-busybox: Update to version 2.34.1.windows.1
  bucket/mingit-busybox.json
  bucket/mingit.json
Labels: review-needed

#674 yori: Change to directly downloading and extracting
  bucket/yori.json
Labels: review-needed

#3018 Add diffsitter 0.6.7
  bucket/diffsitter.json
Labels: review-needed

#2189 Add sourcegraph-cli to bucket
  bucket/sourcegraph-cli.json
Labels: review-needed

#3024 Update postgresql to version 14.1
  bucket/postgresql.json
Labels: package-fix-needed

#2998 qr: Add version 1.0.0
  bucket/qr.json
Labels: not ready

#3028 oh-my-posh3: Update to version 6.19.2
  bucket/oh-my-posh3.json
Labels: review-needed
