Repository ScoopInstaller/Main, pull requests merged in 2021-12, with the labels that each got.

#3029 neovim: update to version 0.6.0
  bucket/neovim.json
Labels: review-needed

#3016 win-acme: update to version 2.1.20.1185 & fix autoupdate field
  bucket/win-acme.json
Labels: review-needed

#3031 oh-my-posh3: Update to version 6.20.0
  bucket/oh-my-posh3.json
Labels: review-needed

#3033 Update to 1.26 and enable exe setting
  bucket/kompose.json
Labels: review-needed

#3034 postgrest: Update to version 9.0.0
  bucket/postgrest.json
Labels: review-needed

#390 llvm: Add `LIBCLANG_PATH` environment variable
  bucket/llvm.json
Labels: package-fix-needed

#3038 win-acme: Fix regex closes #3036
  bucket/win-acme.json
Labels: package-fix-needed

#3039 yt-dlp: update to version 2021.12.01
  bucket/yt-dlp.json
Labels: review-needed

#3040 gdb: Update to version 11.1
  bucket/gdb.json
Labels: package-fix-needed

#554 Add NetCoreDbg
  bucket/netcoredbg.json
Labels: waiting feedback, review-needed

#3043 Added Sonatype Nancy
  bucket/nancy.json
Labels: review-needed

#3051 gleam: Add version 0.17.0
  bucket/gleam.json
Labels: review-needed

#3057 ffmpeg: Fix download URL and update hash
  bucket/ffmpeg.json
Labels: review-needed

#3062 docker: Update to version 20.10.11
  bucket/docker.json
Labels: review-needed

#3067 poetry: Add version 1.1.12
  bucket/poetry.json
Labels: review-needed

#3070 go-containerregistry: Add version 0.7.0
  bucket/go-containerregistry.json
Labels: review-needed

#3074 libxml2: Add version 2.9.3
  bucket/libxml2.json
Labels: review-needed

#3000 diffutils: Use win32 builds
  bucket/diffutils.json
Labels: review-needed

#3079 v2ray: Fix issue in 'path with space'
  bucket/v2ray.json
Labels: review-needed

#3080 chore: Update some very old apps
  bucket/grep.json
  bucket/make.json
  bucket/pcre2grep.json
  bucket/pcregrep.json
  bucket/sed.json
Labels: review-needed

#3081 sort-uniq-wc: Add version 9.0
  bucket/sort-uniq-wc.json
Labels: review-needed

#3083 ncspot: Update to version 0.9.3
  bucket/ncspot.json
Labels: review-needed

#3084 binutils: Add version 2.37
  bucket/binutils.json
  bucket/gawk.json
Labels: review-needed

#3085 htmlq: Add version 0.3.0
  bucket/htmlq.json
Labels: review-needed

#3082 sed, grep: Use choco source
  bucket/grep.json
  bucket/sed.json
Labels: review-needed

#3086 gcc: Add version 11.2.0
  bucket/gcc.json
  bucket/mingw.json
Labels: review-needed

#3052 libvips: Add version 8.12.1
  bucket/libvips.json
Labels: review-needed

#3091 Update pwsh to 7.2.1
  bucket/pwsh.json
Labels: review-needed

#3094 hopp-cli: Add version 0.0.7
  bucket/hopp-cli.json
Labels: review-needed

#3096 es: Add version 1.1.0.20
  bucket/everything-cli.json
Labels: review-needed

#3098 ffmpeg-shared: Fixed download url
  bucket/ffmpeg-shared.json
Labels: review-needed

#3099 clink: Update to version 1.3.0
  bucket/clink.json
Labels: review-needed

#3101 nvm hash conflict
  bucket/nvm.json
Labels: review-needed

#1860 Add PG_LIB_DIR and PG_INCLUDE_DIR env vars
  bucket/postgresql.json
Labels: waiting feedback

#3097 python: Do pip initialization in post_install
  bucket/python.json
Labels: review-needed

#3112 nali: Update to version 0.3.5, fix version detection in url.
  bucket/nali.json
Labels: review-needed

#3119 ffmpeg-shared@4.4.1: Switch to mirrors
  bucket/ffmpeg-shared.json
Labels: review-needed

#3118 ffmpeg@4.4.1: Switch to mirrors
  bucket/ffmpeg.json
Labels: review-needed

#3122 b2: Add version 3.2.0
  bucket/b2.json
Labels: review-needed

#2961 mariadb, redis and forego: Fix manifests and update
  bucket/mariadb.json
  bucket/redis.json
  bucket/redis5.json
  deprecated/forego.json
Labels: review-needed, blocked

#3124 sftpgo: Add version 2.2.0
  bucket/sftpgo.json
Labels: review-needed

#3131 yarn: Update manifest
  bucket/yarn.json
Labels: review-needed

#3126 pdfbox: Update to version 2.0.25
  bucket/pdfbox.json
Labels: review-needed

#3129 schemacrawler: Add version 16.16.5
  bucket/schemacrawler.json
Labels: review-needed

#3133 Add termshark 2.3.0
  bucket/termshark.json
Labels: review-needed
