Repository ScoopInstaller/Main, pull requests merged in 2022-01, with the labels that each got.

#3142 snapraid: Add version 12.0
  bucket/snapraid.json
Labels: review-needed

#3145 argocd-autopilot: Add version 0.2.28
  bucket/argocd-autopilot.json
Labels: review-needed

#3144 krew: Add version 0.4.2
  bucket/krew.json
Labels: review-needed

#3149 janet: Add version 1.19.2
  bucket/janet.json
Labels: review-needed

#3148 mosh-client: Add version 1.3.2
  bucket/mosh-client.json
Labels: review-needed

#3154 coursier: Persist cache and bin
  bucket/coursier.json
Labels: review-needed

#3158 update gibo 2.2.4 -> 2.2.5
  bucket/gibo.json
Labels: review-needed

#3161 cheat: Add version 4.2.3
  bucket/cheat.json
Labels: review-needed

#3155 tealdeer: Add version 1.5.0
  bucket/tealdeer.json
Labels: upstream, review-needed

#3159 scala: update to version 3.1.0
  bucket/scala.json
Labels: review-needed

#3165 argo: add version 3.2.6
  bucket/argo.json
Labels: review-needed

#3166 docker-pushrm: Add version 1.8.0
  bucket/docker-pushrm.json
Labels: review-needed

#3167 opencv: add version 4.5.5
  bucket/opencv.json
Labels: review-needed

#3170 curlie: Add version 1.6.7
  bucket/curlie.json
Labels: review-needed

#3172 pueue: Add version 1.0.6
  bucket/pueue.json
Labels: review-needed

#3171 q: Add version 3.1.6
  bucket/q.json
Labels: review-needed

#3169 Add terraform-docs.json
  bucket/terraform-docs.json
Labels: review-needed

#3173 miller: Add version 6.0.0
  bucket/miller.json
Labels: review-needed

#3175 Update symfony-cli.json
  bucket/symfony-cli.json
Labels: review-needed

#3176 regula: Add version 2.3.0
  bucket/regula.json
Labels: review-needed

#3180 lz4: Add version 1.9.3
  bucket/lz4.json
Labels: review-needed

#3183 winget: Add version 1.2.3411
  bucket/winget.json
Labels: review-needed

#3185 bazel-buildtools: Add version 4.2.5
  bucket/bazel-buildtools.json
Labels: review-needed

#3190 annie: Rename to lux
  bucket/annie.json
  bucket/lux.json
Labels: review-needed

#3187 Create danser-go.json
  bucket/danser-go.json
Labels: review-needed

#3192 Add ghorg 1.7.6
  bucket/ghorg.json
Labels: review-needed

#3193 pnpm: Add version 6.26.1
  bucket/pnpm.json
Labels: review-needed

#3191 podman: Add version 3.4.4
  bucket/podman.json
Labels: review-needed

#3194 pester@5.3.1: Fix manifest
  bucket/pester.json
Labels: review-needed

#3195 openapi-generator-cli: Add version 5.3.1
  bucket/openapi-generator-cli.json
Labels: review-needed

#3196 tailwindcss: Add version 3.0.15
  bucket/tailwindcss.json
Labels: review-needed

#3206 duckdb: Add version 0.3.1
  bucket/duckdb.json
Labels: review-needed

#3204 dbmate: Add version 1.13.0
  bucket/dbmate.json
Labels: review-needed

#3209 xpdf-tools-lsp: Add version 2011-Aug-15
  bucket/xpdf-tools-lsp.json
Labels: review-needed

#3208 meson: Add version 0.61.1
  bucket/meson.json
Labels: review-needed

#3211 lynx@2.9.0dev.10: Fixed download via aria2 failed #3210
  bucket/lynx.json
Labels: review-needed

#3214 multipass: Add version 1.8.0
  bucket/multipass.json
Labels: manifest-fix-needed

#3215 Add jenkins/jenkins-lts
  bucket/jenkins-lts.json
  bucket/jenkins.json
Labels: review-needed

#3207 mpg123: Add version 1.29.3
  bucket/mpg123.json
Labels: review-needed

#3223 chezmoi: Add version 2.10.0
  bucket/chezmoi.json
Labels: review-needed

#3225 autossh: Add version 1.4g
  bucket/autossh.json
Labels: review-needed

#3222 simplex-chat: Add version 1.0.0
  bucket/simplex-chat.json
Labels: review-needed

#3228 Add Terraformer manifest
  bucket/terraformer.json
Labels: review-needed

#3232 chkcpu: Add version 2.14
  bucket/chkcpu.json
Labels: review-needed

#3233 libavif: Add version 0.9.0
  bucket/libavif.json
Labels: review-needed

#3237 infludb: Fix manifest and add influx cli
  bucket/influx.json
  bucket/influxdb.json
  bucket/influxdb2.json
Labels: review-needed

#3238 flux: Rename 'flux2' to 'flux' and move 'fluxctl' to 'Versions'
  bucket/flux.json
  bucket/fluxctl.json
Labels: review-needed

#3240 Kopia: Add version 0.10.1
  bucket/kopia.json
Labels: review-needed

#3242 stylua: Add version 0.11.3
  bucket/stylua.json
Labels: review-needed

#3244 lxc: Add version 4.22
  bucket/lxc.json
Labels: review-needed

#3247 boringproxy: add version 0.8.2
  bucket/boringproxy.json
Labels: review-needed

#3249 ossgadget: Add version 0.1.314
  bucket/ossgadget.json
Labels: review-needed

#3250 gotify-cli: Add version 2.2.1 - gotify-server: Add version 2.1.4
  bucket/gotify-cli.json
  bucket/gotify-server.json
Labels: review-needed

#3251 cosign: Fix hash
  bucket/cosign.json
Labels: review-needed

#3252 sget: Add version 1.5.0 & fix hash
  bucket/sget.json
Labels: review-needed

#3253 ninja-kitware: Add version 1.10.2.g51db2.kitware.jobserver-1
  bucket/ninja-kitware.json
  bucket/ninja.json
Labels: review-needed

#3258 pdfcpu: Add version 0.3.13
  bucket/pdfcpu.json
Labels: review-needed

#3260 MongoDB stable only
  bucket/mongodb.json
Labels: review-needed

#3261 MongoDB: Use jsonpath for checkver
  bucket/mongodb.json
Labels: review-needed

#3262 nomino: Add version 1.1.0
  bucket/nomino.json
Labels: review-needed

#3272 Added aws-nuke
  bucket/aws-nuke.json
Labels: review-needed

#3265 go-swagger: Add version 0.29.0
  bucket/go-swagger.json
Labels: review-needed
