Repository ScoopInstaller/Main, pull requests merged in 2022-04, with the labels that each got.

#3469 yosys: Remove autoupdate, add archive URL & outdated note
  bucket/yosys.json
Labels: review-needed

#3475 scaleway-cli: Update to version 2.5.1, fix autoupdate
  bucket/scaleway-cli.json
Labels: review-needed

#3478 px: Update to version 0.6.1, fix autoupdate
  bucket/px.json
Labels: review-needed

#3483 cheat: Fix autoupdate
  bucket/cheat.json
Labels: review-needed

#3484 Add ytcast
  bucket/ytcast.json
Labels: review-needed

#3486 cmder: handle spaces in %USERPROFILE%
  bucket/cmder-full.json
  bucket/cmder.json
Labels: manifest-fix-needed

#3488 dotter: Update to version 0.12.10, fix autoupdate
  bucket/dotter.json
Labels: review-needed

#3489 gow: Fix checkver, add autoupdate, rearrange bin
  bucket/gow.json
Labels: review-needed

#3491 (chore): Add 7-zip 19.00 helper package
  bucket/7zip19.00-helper.json
Labels: review-needed

#3493 aqtinstall: Add version 2.0.6
  bucket/aqtinstall.json
Labels: review-needed

#3482 uutils: add symlinks for various tools
  bucket/uutils-coreutils-lean.json
  bucket/uutils-coreutils.json
Labels: review-needed

#3495 haskell: Fix JSONPath in checkver
  bucket/haskell.json
Labels: review-needed

#3497 (chore): Suggest ffmpeg
  bucket/yt-dlp.json
Labels: review-needed

#3464 skywalking-cli: Add version 0.10.0
  bucket/skywalking-cli.json
Labels: review-needed

#3492 jdtls: Add version 1.10.0-202204081744
  bucket/jdtls.json
Labels: review-needed

#3503 neovim: Remove regex in checkver
  bucket/neovim.json
Labels: review-needed

#3512 pluto: Update homepage
  bucket/pluto.json
Labels: review-needed

#3498 diff-so-fancy: Add version 1.4.3
  bucket/diff-so-fancy.json
Labels: review-needed

#3515 mob: Update hash extraction url
  bucket/mob.json
Labels: review-needed

#3436 quick-lint-js: Add version 2.4.1
  bucket/quick-lint-js.json
Labels: upstream, review-needed

#3513 nova: Add version 3.0.2
  bucket/nova.json
Labels: review-needed

#3518 ctop: add version 0.7.7
  bucket/ctop.json
Labels: review-needed

#3521 dprint: Add version 0.26.0
  bucket/dprint.json
Labels: review-needed

#3526 zoxide: Update notes
  bucket/zoxide.json
Labels: review-needed

#3517 aspell: Add version 0.60.8-2
  bucket/aspell.json
Labels: review-needed
