Repository ScoopInstaller/Main, pull requests merged in 2024-04, with the labels that each got.

#5672 bun(-baseline): Add version 1.1.0
  bucket/bun-baseline.json
  bucket/bun.json
Labels: review-needed

#5680 bun(-baseline): Merge manifests
  bucket/bun-baseline.json
  bucket/bun.json
Labels: review-needed

#5657 nodejs-lts: fix checkver and add arm64 version
  bucket/nodejs-lts.json
  bucket/nodejs.json
Labels: review-needed

#5661 zstd: Add 32-bit architecture
  bucket/zstd.json
Labels: review-needed

#5682 Fix mozjpeg auto update
  bucket/mozjpeg.json
Labels: review-needed

#5687 rga: Shim `rga-fzf`
  bucket/rga.json
Labels: review-needed

#5690 imagemagick-lean: Fix bins
  bucket/imagemagick-lean.json
Labels: review-needed

#5677 cht@0.7.2: Update cht.exe to 0.7.2 and add auto update.
  bucket/cht.json
Labels: review-needed

#5668 vim: Update to version 9.1.0228
  bucket/vim.json
Labels: review-needed

#5678 Update teleport to version 15.2.0
  bucket/teleport.json
Labels: review-needed

#5604 flamingo: Add version 0.10.2
  bucket/flamingo.json
Labels: review-needed

#5610 px: fix px.ini creation for persist directive
  bucket/px.json
Labels: review-needed

#5706 python: Update to version 3.12.3
  bucket/python.json
Labels: manifest-fix-needed

#5694 haskell: use haskell.org instead of ghc github mirror and update to version 9.8.2
  bucket/haskell.json
Labels: review-needed

#5715 apache: Update to version 2.4.59
  bucket/ab.json
  bucket/apache.json
Labels: review-needed

#5719 MAVEN: Update download URL
  bucket/maven.json
Labels: review-needed

#5704 shinyproxy: Add version 3.0.2
  bucket/shinyproxy.json
Labels: review-needed

#5702 metabase: Add version 0.49.4
  bucket/metabase.json
Labels: review-needed

#5693 swift@5.10: Fix install script
  bucket/swift.json
Labels: review-needed, blocked

#5753 rtools: Update to version 4.4.6104.6039
  bucket/rtools.json
Labels: review-needed

#5742 uutils-coreutils@0.0.23: Update homepage
  bucket/uutils-coreutils.json
Labels: review-needed

#5743 uutils-coreutils-lean@0.0.23: Update homepage
  bucket/uutils-coreutils-lean.json
Labels: review-needed

#5756 Fix exe location in zls.json for version 0.12.0
  bucket/zls.json
Labels: review-needed

#5770 winpython: Fix bins and shortcuts
  bucket/winpython.json
Labels: review-needed

#5734 tlrc: Add version 1.9.1
  bucket/tlrc.json
Labels: review-needed

#5700 kiota: add version 1.13.0
  bucket/kiota.json
Labels: review-needed

#5774 butler: add 15.21.0
  bucket/butler.json
Labels: review-needed

#5727 vim: Change checkver config to stable version
  bucket/vim.json
Labels: review-needed

#5651 granted: Add version 0.24.0
  bucket/granted.json
Labels: review-needed
